# (PART) Data {-}

# Data, variables & experimental designs {#Chap-02-01-data}

The focus of this course is on data from behavioral psychology experiments.^[A *behavioral experiment* is an experiment that records participants' behavioral choices, such as button clicks or linguistic responses in the form of text or speech. This contrasts with, say, *neurological experiments* in which participants' brain activity is recorded, such as fMRI or EEG, or, e.g., in a psycholinguistic context, *processing-related experiments* in which secondary measures of cognitive activity are measured, such as eye-movements, pupil dilation or galvanic skin responses.] In a sense, this is perhaps the most "well-behaved" data to analyze and therefore an excellent starting point into data analysis. However, we should not lose sight of the rich and diverse guises of data that are relevant for scientific purposes. The current chapter therefore starts, in Section \@ref(Chap-02-01-data-kinds-of-data) with sketching some of that richness and diversity. But it then hones in on some basic distinctions of the kinds of data we will frequently deal with in the cognitive sciences in Section \@ref(Chap-02-01-data-variables). We also pick up a few relevant concepts from standard experimental design in Section \@ref(Chap-02-01-data-exp-design) and learn about what makes data tidy in Section \@(Chap-02-01-data-tidy-data).

<!-- TODO: insert references to subsections -->

```{block, type='infobox'}
The learning goals for this chapter are:

- appreciate the diversity of data
- distinguish different kinds of variables
  - dependent vs independent
  - nominal vs ordinal vs metric
- get familiar with basic aspects of experimental design
  - factorial designs
  - within- vs between subjects design
  - repeated measures
  - randomization, fillers and controls
  - sample size
- understand the notion of "tidy data"
```

## Different kinds of data {#Chap-02-01-data-kinds-of-data}

Some say we live in the **data age**. But what is data actually? Purist pedants say: "The plural of datum" and add that a datum is just an observation. But when we say "data" we usually mean a bit more than a bunch of observations. The Merriam-Webster offers the following:

> Factual information (such as measurements or statistics) used as a basis for reasoning, discussion, or calculation.

This is a teleological definition in the sense that it refers to the purpose of the thing: "used as basis for reasoning, discussion, or calculation". This is important, "data" is defined by what we do with it. Another important aspect of this definition is fairly backgrounded, but just as important. We usually consider data to be systematically structured in some way or another. Even when we speak of "raw data", we expect there to be some structure (maybe labels, categories etc.) that distinguishes data from uninterpretable noise. In sum, we can think of data as a represenation of information, stored in a systematic way for the purpose of inference, argument or decision making.

It is easy but wrong to think that data always has to be information based on observations of the world. It is easy to think this because **empirical data**, i.e., data obtained from empirical observation, is the most common form of data (given that it is, arguably, most relevant for decision making and argument). But it is wrong to think this because we can just as well look at **virtual data**. For example, *virtual data* could be **data from computer simulation studies**, e.g., from, say, a 1 billion runs of a multi-agent simulation intended to shed light on the nature of cooperative interaction. It makes sense to analyse such data with the same tools as data from an experiment. We might find out that some parameter constellations in the simulation run are (statistically) most conducive of producing cooperative behavior among our agents, for instance. Another example of *virtual data* is so-called **repeat data** or **fake data** generated from a statistical model, which we can use to test whether that model is any good, in so-called model criticism (see Section \@ref(Chap-03-08-model-criticism)).^[We will later speak of **prior/posterior predictions** for this kind of repeat data.] Finally, **hypothetical data** is data that was neither observed, nor predicted by a model, but something that could have been observed, something that it is merely logically possible to observe, even if it would almost never happen in reality or would not be predicted by any serious model.



- sources of data
  - empirical data vs virtual data
  - observation vs experiment
    - causation vs correlation
    
- what to do with data
  - explanation vs prediction

## On the notion of "variables" {#Chap-02-01-data-variables}

- open/closed categories
- types of variables 
  - dependent vs independent
  - nominal vs ordinal vs metric

## Basics of experimental design {#Chap-02-01-data-exp-design}

- factorial designs
- within- vs between subjects design
- repeated measures
- randomization, fillers and controls
- sample size
  
## Tidy data {#Chap-02-01-data-tidy-data}

- rectangular data
- stages: preprocesssing & cleaning
- wrangling
- long, wide & tidy formats

