
## World Values Survey (wave 6 | 2010-2014)

### Nature, origin and rationale of the data

The [World Values Survey](www.worldvaluessurvey.org) (WVS) aims to study *changing values and their impact on social and political life*. The WVS consists of nationally representative surveys conducted in almost 100 countries which contain almost 90 percent of the world's population, using a common questionnaire. The WVS is the largest non-commercial, cross-national, time series investigation of human beliefs and values.

It currently includes interviews with almost *400,000 respondents*. Respondents are people in the age 18 and older residing within private households in each country, regardless of their nationality, citizenship or language.

The main method of data collection in the WVS survey is *face-to-face interview* at respondent's home / place of residence.

<!-- #### The questionnaire -->

<!-- The survey was conducted by using a *structured* [questionnaire](../4_WV6_Official_Questionnaire.pdf), consisting of 250 questions (here: variables) ([overview of all variables](../3_WV6_Codebook.pdf)) that describe 10 thematic sub-sections: -->

<!-- 1. Perceptions of life, -->
<!-- 2. Environment, -->
<!-- 3. Work, -->
<!-- 4. Family, -->
<!-- 5. Politics and Society, -->
<!-- 6. Religion and Morale, -->
<!-- 7. National Identity, -->
<!-- 8. Security, -->
<!-- 9. Science, and -->
<!-- 10. Socio-demographics. -->

<!-- (The document ["variable description"](../6_variable-description-wvs.csv) contains the assigment of variables to topics.) -->

<!-- #### Theoretical motivation & hypotheses -->

<!-- [**Inglehart's Concept of Postmaterialism**](#postmaterialism-index) -->
<!-- [**Schwartz-Value-Scale**](#value-scale-from-schwartz) -->
<!-- [WORKOUT POSSIBLE HYPOTHESES/ANALYSIS] -->

<!-- ### Loading and preprocessing the data -->

<!-- ```{r wvs loading data set} -->
<!-- d_raw_wvs <- readRDS("data_sets/data-sets/4_world-values-survey/5_WV6.rds") -->
<!-- head(d_raw_wvs) -->
<!-- ``` -->


<!-- #### Postmaterialism Index -->

<!-- "*Inglehart proposes a theory and an index for explaining and tapping the changing value orientations of different societies. Based on the intuition that individual value priorities reflect the level of economic affluence and physical security of society, Inglehart's postmaterialism thesis depicts a process through which economically insecure and traditional societies gradually become more tolerant, egalitarian, participatory, and nurturing. As lower order physiological needs are satisfied and individuals are socialized into more affluent and economically secure societies, traditional materialist values are slowly replaced by higher order, noneconomic concerns-postmaterialist values. (p.649)*" [@davis1999] -->

<!-- **Materialist values**: e.g. physical and economic security, ethnocentrism, low level of tolerance and respect, and the pursuit of prosperity   -->
<!-- **Postmaterialist values**: e.g. pursuit of self-actualization, freedom, emancipation, participation, and quality of life -->

<!-- The Postmaterialism Index is an indicator of the cultural shift from postmaterialistic to materialistic orientation. He is calculated using a 4- or 12-item (here 12-item) battery pertaining to national priorities and policy preferences as perceived by the respondent. -->

<!-- In the [WVS-questionnaire](../4_WV6_Official_Questionnaire.pdf) the 12-item measure is based on the variables V60 to V65: -->

<!-- *Question: People sometimes talk about what the aims of this country should be for the next ten years. On this card are listed some of the goals which different people would give top priority.*  -->

<!-- - **V60** Would you please say which one of these you, yourself, consider the *most important*?  -->
<!-- - **V61** And which would be the *next most important*?  -->

<!-- 1. A high level of economic growth (materialist) -->
<!-- 2. Making sure this country has strong defense forces (materialist) -->
<!-- 3. Seeing that people have more say about how things are done at their jobs and in their communities (post-materialist) -->
<!-- 4. Trying to make our cities and countryside more beautiful (post-materialist) -->

<!-- - **V62** If you had to choose, which one of the things on this card would you say is *most important*?  -->
<!-- - **V63** And which would be the *next most important*?  -->

<!-- 1. Maintaining order in the nation (materialist) -->
<!-- 2. Giving people more say in important government decisions (post-materialist) -->
<!-- 3. Fighting rising prices (materialist) -->
<!-- 4. Protecting freedom of speech (post-materialist) -->

<!-- - **V64** Here is **another list**. In your opinion, which one of these is *most important*?  -->
<!-- - **V65** And what would be the *next most important*?  -->

<!-- 1. A stable economy (materialist) -->
<!-- 2. Progress toward a less impersonal and more humane society (post-materialist) -->
<!-- 3. Progress toward a society in which ideas count more than money (post-materialist) -->
<!-- 4. The fight against crime (materialist) -->

<!-- ##### Defining relevant Variables -->

<!-- As relevant are seen variables for calculating the Postmaterialism Index and further variables that might be interesting for the analysis according to Inglehart's theory on reasons for orientational shift from materialism to postmaterialism. From the wvs data set the following variables are extracted for measuring/calculating:  -->

<!-- - the *Postmaterialism Index*: V60-V65, -->
<!-- - perception of *physical security*: V170, V171-V175, V188-V191,  -->
<!-- - perception of *economic affluence*: V237, V238, V239, and -->
<!-- - further *socio-economic* aspects: V2, V240, V242. -->

<!-- Furthermore only a subset of countries will be considered in analysis.  -->

<!-- ```{r wvs-post select relevant variables} -->
<!-- # select variables for Postmaterialism-Index -->
<!-- d_post_raw <- select(d_raw_wvs,  -->
<!--                        "V60":"V65",    # Postmaterialism Index items -->
<!--                        "V170":"V175",  # Security in neighborhood -->
<!--                        "V237":"V239",  # Saving money, working class, income group -->
<!--                        "V2",           # country -->
<!--                        "V240",         # gender participant -->
<!--                        "V242"          # age participant -->
<!--                        ) %>%  -->
<!--   filter( -->
<!--     V2 %in% c(276,288,124,484,804,156) # Germany, Ghana, Canada, Mexico, Ukraine, China -->
<!--   )  %>%  -->
<!--   as_tibble -->

<!-- # rename variables for better handling -->
<!-- names(d_post_raw) <- c("post_V60","post_V61","post_V62","post_V63","post_V64","post_V65","sec_V170","sec_V171","sec_V172","sec_V173","sec_V174","sec_V175","eco_V237","eco_V238","eco_V239","country_V2","gender_V240", "age_V242")  -->

<!-- # print data set -->
<!-- d_post_raw -->
<!-- ``` -->

<!-- In the WVS missing values are indicated by negative numbers according to the missing type: *Missing; Unknown (-5), Not asked in survey (-4), Not applicable (-3), No answer (-2), don't know (-1)*. For sake of simplicity we will treat all types of missing values equally as *NA*. -->

<!-- ```{r wvs-post inspection of missing values} -->
<!-- # change values c(-5,-4,-3,-2,-1) to NAs -->
<!-- d_post_clean <- replace_with_na_all(d_post_raw, condition = ~.x %in% c(-5,-4,-3,-2,-1)) -->

<!-- # inspect missing values per variable / per respondent -->

<!-- # NA_columns <- sapply(d_post_clean, function(x) sum(is.na(x))) -->
<!-- # NA_rows <- rowSums(is.na(d_post_clean))  -->

<!-- # [HAS TO BE DONE!!!] -->
<!-- ``` -->

<!-- To prepare plotting and also for improving handling of the data, the two socio-demographic variables "country" and "gender" are specified regarding levels and labels. -->

<!-- ```{r wvs-post create factors with levels} -->
<!-- # prepare data set -->
<!-- d_post_clean <- d_post_clean %>%  -->
<!--  mutate( -->
<!--     country = factor(country_V2, levels = c(276,288,124,484,804,156), labels = c("Germany", "Ghana", "Canada", "Mexico", "Ukraine", "China")), -->
<!--     gender = factor(gender_V240, levels = c(1,2), labels = c("female", "male")) -->
<!--   )  -->
<!-- ``` -->

<!-- In the next step, the Postmaterialism Index is calculated. As already introduced above participants had to select out of three different lists, an aim of the country that they judge as "most important" and as "next most important" (in total 6 choices). Furthermore, each aim is associated with a materialistic or postmaterialist orientation (indicated in brackets behind each aim ). Rationale of the calculation is as follows: When the participant choose in all 6 questions a postmaterialist aim, he is characterized as postmaterialist, if he indicates "mostly" postmaterialistic aims he is indicated as rather postmaterialist etc. -->

<!-- For each question is indicated which of the statements is postmaterialistic (condition in the ifelse-statement). If the statement is postmaterialistic the repsondent gets 2 "points" for "most important"-choice (1 "point" for "second most important"-choice) or zero, if aim is materialistic. If a respondent choose only postmaterialistic aims he gets, consequently, the max. number of points "9". Gradings are than marked by "rather postmaterialist", "mixed postmaterialist", etc. -->

<!-- ```{r wvs-post index calculation} -->
<!-- # calculating the postmaterialism-index (12-items) -->
<!-- post_index <- mutate(d_post_clean,  -->
<!--     "post_score" =                       # helper function: first choice = 2/ second choice = 1 -->
<!--       ifelse(post_V60 %in% c(1,2),0,2)+ -->
<!--       ifelse(post_V61 %in% c(1,2),0,1)+ -->
<!--       ifelse(post_V62 %in% c(1,3),0,2)+ -->
<!--       ifelse(post_V63 %in% c(1,3),0,1)+ -->
<!--       ifelse(post_V64 %in% c(1,4),0,2)+ -->
<!--       ifelse(post_V65 %in% c(1,4),0,1),  -->
<!--     "post_index_unord" =                  # calculate postmaterialism-orientation grading  -->
<!--       ifelse(post_score == 9 , "postmaterialist", -->
<!--       ifelse(post_score %in% c(8,7), "rather postmaterialist", -->
<!--       ifelse(post_score %in% c(6,5), "mixed postmaterialist", -->
<!--       ifelse(post_score %in% c(4,3), "mixed materialist", -->
<!--       ifelse(post_score %in% c(2,1), "rather materialist", -->
<!--       "materialist" -->
<!--     ))))), -->
<!--     "post_index" = factor(post_index_unord, levels = c("postmaterialist","rather postmaterialist","mixed postmaterialist","mixed materialist","rather materialist","materialist", ordered = TRUE)) -->
<!--     ) %>%   -->
<!--   print() -->
<!-- ``` -->

<!-- For a first overview we can have an overview of the distribution of the postmaterialistic orientation in Germany. -->

<!-- ```{r wvs-post distribution: Germany} -->
<!-- # distribution of postmaterialists-types in population  -->
<!-- post_index %>%  -->
<!--   filter( -->
<!--     country == "Germany" -->
<!--   ) %>%  -->
<!--   group_by(`post_index`) %>%  -->
<!--   summarize(count = n(), -->
<!--             percentage = scales::percent(count/2046)   # HOW TO CALL LENGTH??? -->
<!--             ) %>%  -->
<!--   as_tibble()  -->
<!-- ``` -->

<!-- Now, we can have a look at different countries and in how far they differ from each other: -->

<!-- ```{r wvs-post bar chart grouped by country, fig.cap= "Postmaterialism Index grouped by Germany, US, Japan and South Africa" } -->
<!-- # bar chart grouped by country -->
<!-- post_index %>%  -->
<!--   ggplot(mapping = aes(x = post_index, y = (..count..)/sum(..count..), fill = country)) + -->
<!--     geom_bar(position = "fill") + -->
<!--     scale_x_discrete(labels = c("postmaterialist",2, 3, 4, 5, "materialist")) + -->
<!--     ylab("Percentage") + -->
<!--     ggtitle("Postmaterialism-Index: Comparision between countries") -->
<!-- ``` -->

<!-- Focussing on gender: Is there any influence of "gender" on postmaterialist orientation across countries? -->

<!-- ```{r wvs-post bar chart gender difference and country, fig.cap= "Postmaterialism Index across countries grouped by gender"} -->
<!-- # bar char grouped by gender -->
<!-- post_index %>%  -->
<!--   #filter(country == "Germany") %>% -->
<!--   ggplot(mapping = aes(x = post_index, y = (..count..)/sum(..count..), fill = gender)) + -->
<!--   geom_bar(position = "dodge") + -->
<!--   scale_x_discrete(labels = c("postmaterialist",2, 3, 4, 5, "materialist")) + -->
<!--   facet_wrap(~country, nrow = 3) + -->
<!--   ylab("Percentage") + -->
<!--   xlab("Postmaterialism-Index") + -->
<!--   ggtitle("Postmaterialism-Index:Gender difference across countries") -->
<!-- ``` -->


<!-- ```{r wvs-post boxplot age difference and country, fig.cap="Postmaterialism-Index across countries depending on age"} -->
<!-- # variable: "working-class" with 1 - upper class to 5 - lower class -->
<!-- post_index %>%  -->
<!-- ggplot(mapping = aes(x = post_index , y = age_V242)) + -->
<!--   geom_boxplot() + -->
<!--   scale_x_discrete(labels = c("postmaterialist",2, 3, 4, 5, "materialist")) + -->
<!--   ylab("Age of participant") + -->
<!--   xlab("Postmaterialism-Index") + -->
<!--   facet_wrap(~country, nrow = 3) + -->
<!--   ggtitle("Postmaterialism-Index across countries and participant's age") -->
<!-- ``` -->

<!-- According to Inglehart, higher perception of physical and economic security leads to increased postmaterialistic orientation. In order to analyse this assumption, let us inspect, in the first step, one example item of the WVS that measures **physical security**: -->

<!-- - **sec_V170**: Could you tell me how secure do you feel these days in your neighborhood ? (from 1-very to 4-not at all secure) -->
<!-- - **sec_V171-V175**: How frequently do the following things occur in your neighborhood? (from 1-very to 4-not at all frequently) -->
<!--  + Robberies -->
<!--  + Alcohol consumption in the streets -->
<!--  + Police or military interfere with people's private life -->
<!--  + Racist behavior -->
<!--  + Drug sale in streets -->

<!-- We create a new variable indicating the "violence frequency in neighborhood" by taking the median of the variables sec_V171-V175.  -->

<!-- ```{r wvs-post create variable "violence_neighborhood"} -->
<!-- post_index %>%  -->
<!--   rowwise() %>%  -->
<!--   mutate( -->
<!--     violence_neighborhood = median(c(sec_V171,sec_V172,sec_V173, sec_V174, sec_V175)) -->
<!--   ) -> post_index -->
<!-- ``` -->

<!-- In order to analyse the relation between both "security" variables we can plot in a first step the overall perception of security in neighborhood. -->

<!-- ```{r wvs-post barchart security perception in neighborhood across countries, fig.cap="Security perception in neighborhood across countries"} -->
<!-- # security perception: How secure do you feel these days in your neighborhood? -->
<!-- post_index %>%  -->
<!--   ggplot(mapping = aes(x = sec_V170, y = (..count..)/sum(..count..))) + -->
<!--     geom_bar(position = "dodge") + -->
<!--     facet_wrap(~ country, nrow = 2) + -->
<!--     scale_x_continuous(name = "security perception", breaks = c(1,2,3,4), labels = c("very", 2, 3, "not at all")) + -->
<!--     ylab("Percentage") + -->
<!--     ggtitle("Security Perception accross countries") -->
<!-- ``` -->

<!-- In a second step we can make the same plot for the rating of "frequency of violence in neighborhood". (Be careful with the difference of the rating scale of both variables.) -->

<!-- ```{r wvs-post bar chart violence perception in neighborhood across countries, fig.cap="Frequency of violence in neighborhood across countries" } -->
<!-- # violence perception: How frequently do the following things occur in your neighborhood? -->
<!-- post_index %>%  -->
<!--   ggplot(mapping = aes(x = security_neighborhood, y = (..count..)/sum(..count..))) + -->
<!--     geom_bar(position = "dodge") + -->
<!--     facet_wrap(~ country, nrow = 2) + -->
<!--     scale_x_continuous(name = "Frequency of violence perception", breaks = c(1,2,3,4), labels = c("very", 2, 3, "not at all")) + -->
<!--     ylab("Percentage") + -->
<!--     ggtitle("Frequency of violence in neigborhood accross countries") -->
<!-- ``` -->

<!-- In the second step, we can inspect further example item of the WVS that measures **economic security**: -->

<!-- - **eco_V239**: On this card is an income scale on which 1 indicates the lowest income group and 10 the highest -->
<!-- income group in your country. We would like to know in what group your household is -->

<!-- ```{r wvs-post bar chart income class grouped by gender across countries, fig.cap="Income situation of respondents across countries and grouped by gender"} -->
<!-- # economic situation: Income scale on which 1 indicates the lowest income group and 10 the highest income group -->
<!-- post_index %>%  -->
<!--   ggplot(mapping = aes(x = eco_V239, y = (..count..)/sum(..count..), fill = gender)) + -->
<!--     geom_bar(position = "dodge") + -->
<!--     facet_wrap(~ country, nrow = 2) + -->
<!--     ylab("Percentage") + -->
<!--     xlab("Income scale (1-lowest, 10-highest)") + -->
<!--     ggtitle("Income situation of respondents accross countries") -->
<!-- ``` -->

<!-- <!-- ##### Testing hypotheses --> -->

<!-- <!-- ```{r} --> -->
<!-- <!-- # data for 20-69 years old participant in Germany and China --> -->
<!-- <!-- d_test <- post_index %>%  --> -->
<!-- <!--   filter(age_V242 >= 20 & age_V242 < 70 & country %in% c("Germany","Ghana")) %>%  --> -->
<!-- <!--  mutate("post_score" =                       # helper function: first choice = 2/ second choice = 1 --> -->
<!-- <!--       ifelse(post_V60 %in% c(1,2),0,2)+ --> -->
<!-- <!--       ifelse(post_V61 %in% c(1,2),0,1)+ --> -->
<!-- <!--       ifelse(post_V62 %in% c(1,3),0,2)+ --> -->
<!-- <!--       ifelse(post_V63 %in% c(1,3),0,1)+ --> -->
<!-- <!--       ifelse(post_V64 %in% c(1,4),0,2)+ --> -->
<!-- <!--       ifelse(post_V65 %in% c(1,4),0,1) --> -->
<!-- <!--     ) %>%   --> -->
<!-- <!--   group_by(age_V242, country) %>%  --> -->
<!-- <!--   summarise( --> -->
<!-- <!--     post_median = median(post_score), --> -->
<!-- <!--     sec_V170_med = median(sec_V170),  --> -->
<!-- <!--     eco_V239_med = median(eco_V239), --> -->
<!-- <!--     eco_V237_med = median(eco_V237), --> -->
<!-- <!--     post_index = median(post_score) --> -->
<!-- <!--   ) %>% na.omit() %>% print()  --> -->
<!-- <!-- ``` --> -->
<!-- <!-- ```{r} --> -->
<!-- <!-- # overall  --> -->
<!-- <!-- model1 <- post_index ~ country --> -->
<!-- <!-- model2 <- post_index ~ (sec_V170_med + eco_V237_med)|country --> -->

<!-- <!-- m1 <- brm(formula = model1, family = "categorical", data = d_test, chains = 2) --> -->

<!-- <!-- m2 <- brm(formula = model2, family = "categorical", data = d_test, chains = 2) --> -->

<!-- <!-- summary(m1) --> -->

<!-- <!-- # include age? --> -->
<!-- <!-- # [WORK OUT - NOT FINISHED!] --> -->
<!-- <!-- ``` --> -->

<!-- #### Value Scale from Schwartz -->

<!-- Schwartz identifies *ten different values* which can be summarized in two fundamental polarities along which these values cluster: **egoism** versus **altruism** (in Schwartz's terminology: self-enhancement vs. self-transcendence) and **conformism** versus **individualism** (conservation vs. openness to change). The first dimension includes values such as *power* and *achievement* (egoism) and *benevolence* and *universalism* (altruism); *stimulation* and *self-direction* (individualism) and *security* and *conformity* (conformism) form the second dimension. -->

<!-- **Schwartz Value Inventory (SVI) items** in the wvs-questionnaire: -->

<!-- *Question: Would you please indicate for each description whether that person is very much like you, like you, somewhat like you, a little like you, not like you, or not at all like you? (6-point Likert-scale)* -->

<!-- 1. V70: It is important to this person to think up new ideas and be creative; to do things one's own way. (Self-Direction) -->
<!-- 2. V71: It is important to this person to be rich; to have a lot of money and expensive things. (Power) -->
<!-- 3. V72: Living in secure surroundings is important to this person; to avoid anything that might be dangerous. (Security) -->
<!-- 4. V73: It is important to this person to have a good time; to "spoil" oneself. (Hedonism) -->
<!-- 5. V74: It is important to this person to do something for the good of society. (Benevolence) -->
<!-- 6. V74B: It is important for this people to help the people nearby; to care for their well-being (Benevolence) -->
<!-- 7. V75: Being very successful is important to this person; to have people recognize one's achievements. (Achievement) -->
<!-- 8. V76: Adventure and taking risks are important to this person; to have an exciting life. (Stimulation) -->
<!-- 9. V77: It is important to this person to always behave properly; to avoid doing anything people would say is wrong. (Conformity) -->
<!-- 10. V78: Looking after the environment is important to this person; to care for nature and save life resources. (Universalism) -->
<!-- 11. V79: Tradition is important to this person; to follow the customs handed down by one's religion or family. (Tradition) -->

<!-- [WORKOUT] -->

<!-- ```{r wvs-schwartz select relevant variables} -->
<!-- # select variables for Schwartz-value-scale -->
<!-- d_value_raw <- select(d_raw_wvs, -->
<!--                        "V70":"V79",    # scale items -->
<!--                        "V2",           # country -->
<!--                        "V238",         # working-class participant -->
<!--                        "V242",         # age of participant -->
<!--                        "V240"          # gender of participant -->
<!--                        ) %>% -->
<!--   filter( -->
<!--     V2 %in% c(276,288,124,484,804,156) # Germany, Ghana, Canada, Mexico, Ukraine, China -->
<!--   ) %>% -->
<!--   as_tibble() %>% -->
<!--   print() -->
<!-- ``` -->

<!-- ```{r wvs-schwartz inspect missing data} -->
<!-- # change values c(-5,-4,-3,-2,-1) to NAs -->
<!-- d_value_clean <- replace_with_na_all(d_value_raw, condition = ~.x %in% c(-5,-4,-3,-2,-1)) -->

<!-- # inspect missing values per country and variable (item) -->
<!-- d_value_clean %>% -->
<!--   summary() -->
<!-- ``` -->
<!-- ```{r wvs-schwartz create new "benevolence" variable out of two different variables } -->
<!-- # use V74 or V74B, depending on NA -->
<!-- d_value_clean <- d_value_clean %>% -->
<!--   mutate(V74_new = ifelse(is.na(V74)==FALSE,V74,V74B)) %>% -->
<!--   print() -->
<!-- ``` -->

<!-- ```{r wvs-schwartz prepare tibble for plotting} -->
<!-- # prepare tibble -->
<!-- d_value_clean <- -->
<!--  transmute(d_value_clean, -->
<!--     power = factor(V71), -->
<!--     achievement = factor(V75), -->
<!--     universalism = factor(V78), -->
<!--     benevolence = factor(V74_new), -->
<!--     self_direction =  factor(V70), -->
<!--     stimulation = factor(V76), -->
<!--     security = factor(V72), -->
<!--     conformity = factor(V77), -->
<!--     hedonism = factor(V73), -->
<!--     tradition = factor(V79), -->
<!--     country = factor(V2, levels = c(276,288,124,484,804,156), labels = c("Germany","Ghana","Canada","Mexico","Ukraine", "China")), -->
<!--     gender = factor(V240, levels = c(1,2), labels = c("female", "male")), -->
<!--     working_class = factor(V238, levels = c(1,2,3,4,5), labels = c("Upper class","Upper middle class","Lower middle class","Working class","Lower class")), -->
<!--     age = V242 -->
<!--   ) %>% -->
<!--   print() -->
<!-- ``` -->

<!-- ```{r wvs-schwartz create dimensions according to Schwartz} -->
<!-- d_value_clean %>%  -->
<!--   rowwise() %>%  -->
<!--   mutate( -->
<!--     dim_egoism = median(c(power,achievement)), -->
<!--     dim_altruism = median(c(universalism,benevolence)), -->
<!--     dim_individualism = median(c(self_direction,stimulation)), -->
<!--     dim_conformism = median(c(security,conformity)) -->
<!--   ) -> d_value_clean  -->
<!-- ``` -->

<!-- ```{r wvs-schwartz group tibble by single values} -->
<!-- # rearrange tibble for plotting -->
<!-- d_value_clean1 <- d_value_clean %>% -->
<!--   pivot_longer( -->
<!--     cols = power:tradition, -->
<!--     names_to = "value", -->
<!--     values_to = "rating" -->
<!--   ) %>% -->
<!--   print() -->
<!-- ``` -->

<!-- ```{r wvs-schwartz group tibble by dimensions} -->
<!-- # rearrange tibble for plotting -->
<!-- d_value_clean2 <- d_value_clean %>% -->
<!--   pivot_longer( -->
<!--     cols = dim_egoism:dim_conformism, -->
<!--     names_to = "dimension", -->
<!--     values_to = "rating_dim" -->
<!--   ) %>% -->
<!--   print() -->
<!-- ``` -->

<!-- ```{r wvs-schwartz flipped bar chart values in Germany, fig.cap="Values in Germany (How much do you identify with the following value?) "} -->
<!-- # flipped bar chart -->
<!-- d_value_clean1 %>% -->
<!--   na.omit() %>% -->
<!--   filter(country == "Germany") %>% -->
<!-- ggplot(mapping = aes(x = rating, y = (..count..)/sum(..count..), fill = rating)) + -->
<!--   geom_bar( -->
<!--     show.legend = FALSE, -->
<!--     width = 1 -->
<!--   ) + -->
<!--   theme(aspect.ratio = 1) + -->
<!--   labs(x = NULL, y = NULL) + -->
<!--   coord_flip() + -->
<!--   facet_wrap(~ value, nrow = 2) + -->
<!--   ggtitle("Value scale: Germany (1-very much to 6-not at all)") -->
<!-- ``` -->

<!-- ```{r wvs-schwartz coxcomb chart values Germany, fig.cap="Values in Germany (How much do you identify with the following value?)"} -->
<!-- # Bar chart and Coxcomb chart -->
<!-- d_value_clean1 %>% -->
<!--   na.omit() %>% -->
<!--   filter(country == "Germany") %>% -->
<!-- ggplot(mapping = aes(x = rating, y = (..count..)/sum(..count..), fill = rating)) + -->
<!--   geom_bar( -->
<!--     show.legend = FALSE, -->
<!--     width = 1 -->
<!--   ) + -->
<!--   theme(aspect.ratio = 1) + -->
<!--   labs(x = NULL, y = NULL) + -->
<!--   coord_polar() + -->
<!--   facet_wrap(~ value, nrow = 2) + -->
<!--   ggtitle("Value scale: Germany") -->
<!-- ``` -->

<!-- ```{r wvs-schwartz bar value-dimensions across countries and gender, fig.cap="Value dimensions across countries (How much do you identify with the following value?) and grouped by gender"} -->
<!-- # bar chart -->
<!-- d_value_clean2 %>% -->
<!--   na.omit() %>% -->
<!--   filter( -->
<!--     country %in% c("Germany", "China") -->
<!--   ) %>%  -->
<!-- ggplot(mapping = aes(x = rating_dim, y = (..count..)/sum(..count..), fill = gender)) + -->
<!--   geom_bar(position = "identity", alpha = .8) + -->
<!--   facet_wrap(country ~ dimension, nrow = 2) + -->
<!--   ylab("Percentage") + -->
<!--   scale_x_continuous(name = "Identification with value (1-very much to 6-not at all", breaks = c(1,2,3,4,5,6), labels = c("very much", 2, 3, 4, 5, "not at all")) + -->
<!--   ggtitle("Value-Dimensions across countries") -->
<!-- ``` -->

<!-- ```{r wvs-schwartz bar values across countries, fig.cap="Single values across countries (How much do you identify with the following value?) and grouped by gender"} -->
<!-- # bar chart - grouped by countries and values -->
<!-- d_value_clean1 %>% -->
<!--   na.omit() %>% -->
<!--   filter(country %in% c("Germany", "China", "Ghana")) %>% -->
<!-- ggplot(mapping = aes(x = rating, y = (..count..)/sum(..count..), fill = country)) + -->
<!--   geom_bar(position = "identity", alpha = .7) + -->
<!--   facet_wrap(~ value, nrow = 3) + -->
<!--   scale_x_discrete(labels = c(1,2,3,4,5,6)) + -->
<!--   ylab("percentage") + -->
<!--   ggtitle("Value scale: Germany, China, Ghana (1-very much to 6-not at all)") -->
<!-- ``` -->

<!-- <!-- ```{r} --> -->
<!-- <!-- d_value_test <- d_value_clean2 %>% --> -->
<!-- <!--   filter(country == "Germany" & age >= 20 & age < 70 & dimension %in% c("dim_altruism", "dim_egoism")) %>%  --> -->
<!-- <!--   select(dimension,age,working_class,rating_dim) %>%  --> -->
<!-- <!--   na.omit() %>%  --> -->
<!-- <!--   group_by(age, dimension) %>%  --> -->
<!-- <!--   summarize( --> -->
<!-- <!--     rating_med = factor(median(rating_dim), ordered = TRUE) --> -->
<!-- <!--   ) %>% print() --> -->
<!-- <!-- ``` --> -->

<!-- <!-- ```{r} --> -->
<!-- <!-- model1_value <- rating_med ~ age|dimension --> -->

<!-- <!-- brm(formula = model1_value, data = d_value_test, family = "cumulative", chains = 2) --> -->
<!-- <!-- ``` --> -->

